require('aerial').setup {
  backends = { 'lsp', 'treesitter', 'markdown' },
  close_behavior = 'auto',
  default_bindings = true,
  default_direction = 'right',
  filter_kind = {
    'Class',
    'Constructor',
    'Enum',
    'Function',
    'Interface',
    'Method',
    'Struct',
    'Variable',
    'Constant',
  },
  highlight_mode = 'split_width',
  highlight_on_jump = 500,
  link_tree_to_folds = false,
  link_folds_to_tree = false,
  manage_folds = false,
  max_width = 60,
  min_width = 30,
  nerd_font = true,
  open_automatic = false,
  open_automatic_min_lines = 0,
  open_automatic_min_symbols = 0,
  placement_editor_edge = true,
  post_jump_cmd = 'normal! zz',
  close_on_select = false,
  float = {
    border = 'rounded',
    row = 1,
    col = 0,
    max_height = 100,
    min_height = 4,
  },
  lsp = {
    diagnostics_trigger_update = true,
    update_when_errors = true,
  },
  treesitter = {
    update_delay = 300,
  },
  markdown = {
    update_delay = 300,
  },
}
