-- { "Dave-Elec/gruvbox" }
-- { "dstein64/vim-startuptime" }
-- { "haringsrob/nvim_context_vt" }
-- { "jbyuki/instant.nvim" }
-- { "jubnzv/virtual-types.nvim" }
-- { "kevinhwang91/nvim-bqf" }
-- { "lilyinstarlight/vim-sonic-pi" }
-- { "mattn/emmet-vim" }
-- { "metakirby5/codi.vim" }
-- { "ntk148v/vim-horizon" }
-- { "nvim-telescope/telescope-media-files.nvim" }
-- { "sbdchd/neoformat" }
-- { "vimwiki/vimwiki" }
-- { "voldikss/vim-floaterm" }
-- { "NTBBloodbath/rest.nvim", config = function() require('rest-nvim').setup() vim.api.nvim_set_keymap("n", "<leader>rn", "<cmd>lua require('rest-nvim').run()<CR>", {noremap = true, silent = true}) end } use { "nacro90/numb.nvim", config = function() require('numb').setup { show_numbers = true, -- Enable 'number' for the window while peeking show_cursorline = true, -- Enable 'cursorline' for the window while peeking number_only = false -- Peek only when the command is only a number instead of when it starts with a number } end }
-- { "SmiteshP/nvim-gps", requires = "nvim-treesitter/nvim-treesitter", config = function() require("nvim-gps").setup({ icons = { ["class-name"] = ' ', -- Classes and class-like objects ["function-name"] = ' ', -- Functions ["method-name"] = ' ' -- Methods (functions inside class-like objects) }, languages = {}, separator = ' -> ' }) end }
-- { "ayu-theme/ayu-vim", config = function() vim.g.ayucolor = "mirage" _G.toggle_ayucolor = function() if vim.g.ayucolor_num == nil then vim.g.ayucolor_num = 0 end local colors = {'mirage', 'dark', 'light'} ---@diagnostic disable-next-line: undefined-field vim.g.colo_num = ((vim.g.colo_num % table.getn(colors)) + 1) vim.g.ayucolor = colors[vim.g.colo_num] vim.api.nvim_exec("colorscheme ayu", false) print(vim.g.ayucolor) end end }
-- { "dsznajder/vscode-es7-javascript-react-snippets", run = "yarn install --frozen-lockfile && yarn compile" }
-- { "f-person/git-blame.nvim", config = function() vim.g.gitblame_enabled = false end }
-- { "kevinhwang91/rnvimr", config = function() vim.cmd [[ tnoremap <silent> <M-i> <C-\><C-n>:RnvimrResize<CR> nnoremap <silent> <M-o> :RnvimrToggle<CR> tnoremap <silent> <M-o> <C-\><C-n>:RnvimrToggle<CR> ]] --   end, cmd = {'RnvimrToggle'} }
-- { "marko-cerovac/material.nvim", config = function() vim.g.material_borders = true vim.g.material_contrast = true vim.g.material_disable_background = false vim.g.material_italic_comments = true vim.g.material_italic_functions = true vim.g.material_italic_keywords = true vim.g.material_italic_variables = false vim.g.material_style = 'deep ocean' vim.api.nvim_set_keymap('n', '<leader>m', ":lua require('material.functions').toggle_style(true)<CR>", {noremap = true, silent = true}) end }
-- { "onsails/lspkind-nvim", config = function() require"lspkind".init({}) end }
-- { "rmagatti/goto-preview", config = function() require('goto-preview').setup { width = 120, -- Width of the floating window height = 15, -- Height of the floating window default_mappings = true, -- Bind default mappings debug = false, -- Print debug information opacity = nil -- 0-100 opacity level of the floating window where 100 is fully transparent. } end }
-- { "romgrk/nvim-treesitter-context", config = function() require'treesitter-context'.setup {enable = true, throttle = true} end }
-- { "shaunsingh/moonlight.nvim", config = function() vim.g.moonlight_borders = true vim.g.moonlight_contrast = true vim.g.moonlight_disable_background = false vim.g.moonlight_italic_comments = true vim.g.moonlight_italic_functions = true vim.g.moonlight_italic_keywords = true vim.g.moonlight_italic_variables = false end }
-- { "simrat39/symbols-outline.nvim", config = function() vim.g.symbols_outline = { highlight_hovered_item = true, show_guides = true, auto_preview = false, -- experimental position = 'right', keymaps = { close = "q", goto_location = "<Cr>", focus_location = "o", hover_symbol = "<C-space>", rename_symbol = "r", code_actions = "a" }, lsp_blacklist = {} } vim.api.nvim_set_keymap("n", "<M-s>", ":SymbolsOutline<CR>", {noremap = true, silent = true}) end, cmd = {'SymbolsOutline'} }
-- { 'glacambre/firenvim', run = function() vim.fn['firenvim#install'](0) end }
-- { 'tzachar/compe-tabnine', run = './install.sh', requires = 'hrsh7th/nvim-compe' }
-- { "dracula/vim", as = "dracula" }
-- { "glepnir/galaxyline.nvim", branch = "main" }
-- { "michaelb/sniprun", run = "bash ./install.sh" }
-- { "nvim-treesitter/nvim-treesitter-refactor" }
-- { "pianocomposer321/yabs.nvim" }
-- { 'rcarriga/nvim-notify' }
-- { 'nvim-neorg/neorg', config = "require 'plugins.editing.neorg'", requires = { 'nvim-lua/plenary.nvim' }, },
-- { 'TimUntersberger/neofs', config = function() require('plugins.explorer').neofs() end, keys = { { 'n', '<leader>FF' }, { 'n', '<leader>FN' }, }, },
-- { 'camspiers/snap', keys = { { 'n', '<leader><leader>' }, { 'n', '<leader>fg' }, { 'n', '<leader>fb' }, { 'n', '<leader>fo' }, { 'n', '<leader>fn' }, }, config = function() require('plugins.explorer').snap() end, disable = true, },
-- { 'tamago324/lir.nvim', requires = { { 'tamago324/lir-git-status.nvim', config = function() require('lir.git_status').setup { show_ignored = true, } end, keys = { { 'n', '<M-e>' }, { 'n', '<M-n>' }, }, }, }, config = function() require('plugins.explorer').lir() end, keys = { { 'n', '<M-e>' }, { 'n', '<M-n>' }, }, },
-- { 'stevearc/gkeep.nvim', run = ':UpdateRemotePlugins', cmd = { 'GkeepOpen', 'GkeepToggle', }, },
-- { -- refactoring 'ThePrimeagen/refactoring.nvim', config = function() require('refactoring').setup {} end, ft = { 'go', 'javascript', 'typescript', 'lua', 'python', 'c', 'cpp', }, },
-- { -- Jabs 'matbme/JABS.nvim', config = require('utilities').jabs, cmd = { 'JABS', 'JABSOpen', 'J' }, keys = { { 'n', '<C-b>' } }, },
-- { -- vim-workman 'nicwest/vim-workman', cmd = { 'Workman', 'Workman!', 'Qwerty', 'Qwerty!' }, config = "require 'plugins.editing.workman'", },
-- { 'nvim-pack/nvim-spectre', disable = true },
-- { -- presenting 'sotte/presenting.vim', ft = { 'markdown' }, config = function() vim.cmd [[ augroup presentation autocmd! autocmd Filetype markdown nnoremap <buffer> <C-p> :PresentingStart<CR> autocmd Filetype markdown nnoremap <buffer> <C-c> :.!toilet -w 200 -f term -F border<CR> augroup end ]] end, },
-- { 'tpope/vim-repeat', event = 'BufWinEnter' },
