return {
    ['@attribute'] = { fg = 'text' },
    ['@attribute.builtin'] = { bold = false },
    ['@constant.builtin'] = { bold = false },
    ['@function'] = { fg = 'rose' },
    ['@function.builtin'] = { fg = 'text', bold = false },
    ['@function.call.python'] = { fg = 'text', bold = false },
    ['@function.method'] = { link = 'Normal' },
    ['@function.method.call'] = { link = 'Normal' },
    ['@keyword.coroutine.python'] = { italic = true },
    ['@keyword.exception'] = { fg = 'love' },
    ['@keyword.import'] = { fg = 'text' },
    ['@lsp.type.decorator'] = { link = 'Normal' },
    ['@lsp.type.function'] = { link = '@lsp' },
    ['@lsp.type.selfParameter'] = { fg = 'foam' },
    ['@lsp.type.variable'] = { bold = false },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@lsp' },
    ['@lsp.typemod.function.definition'] = { fg = 'rose' },
    ['@lsp.typemod.method.definition'] = { fg = 'rose', bold = false },
    ['@lsp.typemod.selfParameter.definition'] = { fg = 'foam' },
    ['@parameter'] = { italic = false },
    ['@property'] = { link = 'Normal' },
    ['@type.builtin'] = { bold = false },
    ['@variable'] = { fg = 'text', italic = false },
    ['@variable.builtin'] = { fg = 'text', bold = false, italic = false },
    ['@variable.member'] = { fg = 'text', bold = false },
    ['@variable.parameter'] = { italic = false },

    -- bash
    ['@constant.bash'] = { fg = 'foam' },
    ['@function.builtin.bash'] = { fg = 'text' },
    ['@function.call.bash'] = { fg = 'text' },
    ['@keyword.conditional.bash'] = { fg = 'text' },
    ['@keyword.repeat.bash'] = { fg = 'text' },
    ['@operator.bash'] = { fg = 'text' },
}
