return {
    -- python
    ['@attribute.python'] = { fg = 'text' },
    ['@attribute.builtin.python'] = { bold = false },
    ['@constant.builtin.python'] = { bold = false },
    ['@function.python'] = { fg = 'rose' },
    ['@function.builtin.python'] = { fg = 'text', bold = false },
    ['@function.call.python'] = { fg = 'text', bold = false },
    ['@function.method.python'] = { link = 'Normal' },
    ['@function.method.call.python'] = { link = 'Normal' },
    ['@keyword.conditional.python'] = { link = '@lsp' },
    ['@keyword.coroutine.python'] = { italic = true },
    -- ['@keyword.exception'] = { fg = 'love' },
    ['@keyword.exception.python'] = { link = '@lsp' },
    ['@keyword.import.python'] = { fg = 'text' },
    ['@lsp.type.decorator.python'] = { link = 'Normal' },
    ['@lsp.type.function.python'] = { link = '@lsp' },
    ['@lsp.type.selfParameter.python'] = { fg = 'foam' },
    ['@lsp.type.variable.python'] = { bold = false },
    ['@lsp.typemod.function.defaultLibrary.python'] = { link = '@lsp' },
    ['@lsp.typemod.function.definition.python'] = { fg = 'rose' },
    ['@lsp.typemod.method.definition.python'] = { fg = 'rose', bold = false },
    ['@lsp.typemod.selfParameter.definition.python'] = { fg = 'foam' },
    ['@parameter.python'] = { italic = false },
    ['@property.python'] = { link = 'Normal' },
    ['@type.builtin.python'] = { bold = false },
    ['@variable.python'] = { fg = 'text', italic = false },
    ['@variable.builtin.python'] = { fg = 'text', bold = false, italic = false },
    ['@variable.member.python'] = { fg = 'text', bold = false },
    ['@variable.parameter.python'] = { italic = false },

    -- bash
    ['@constant.bash'] = { fg = 'foam' },
    ['@function.builtin.bash'] = { fg = 'text' },
    ['@function.call.bash'] = { fg = 'text' },
    ['@keyword.conditional.bash'] = { fg = 'text' },
    ['@keyword.repeat.bash'] = { fg = 'text' },
    ['@operator.bash'] = { fg = 'text' },
}
