return {
    ['@attribute.builtin'] = { bold = false },
    ['@function'] = { link = 'Normal' },
    ['@function.method'] = { link = 'Normal' },
    ['@function.method.call'] = { link = 'Normal' },
    ['@keyword.coroutine.python'] = { italic = true },
    ['@keyword.exception'] = { fg = 'love' },
    ['@lsp.type.decorator'] = { link = 'Normal' },
    ['@lsp.type.variable'] = { bold = false },
    ['@lsp.typemod.method.definition'] = { fg = 'rose' },
    ['@parameter'] = { italic = false },
    ['@property'] = { link = 'Normal' },
    ['@variable'] = { fg = 'text', italic = false },
    ['@variable.builtin'] = { fg = 'text', bold = false, italic = false },
    ['@variable.member'] = { fg = 'text', bold = true },
    ['@variable.parameter'] = { italic = false },
    ['@type.builtin'] = { bold = false },
    ['@lsp.typemod.selfParameter.definition'] = { fg = 'foam' },
    ['@lsp.type.selfParameter'] = { fg = 'foam' },
}
